// Phase 1 - RBAC Foundation

// Section 1 — Permission Constants
export const PERMISSIONS = {
  VIEW_DASHBOARD: 'VIEW_DASHBOARD',
  ACCESS_ADMIN_DASHBOARD: 'ACCESS_ADMIN_DASHBOARD',
  VIEW_PRODUCTS: 'VIEW_PRODUCTS',
  EDIT_PRODUCTS: 'EDIT_PRODUCTS',
  DELETE_PRODUCTS: 'DELETE_PRODUCTS',
  VIEW_ORDERS: 'VIEW_ORDERS',
  EDIT_ORDERS: 'EDIT_ORDERS',
  PROCESS_ORDERS: 'PROCESS_ORDERS',
  VIEW_PRESCRIPTIONS: 'VIEW_PRESCRIPTIONS',
  VERIFY_PRESCRIPTIONS: 'VERIFY_PRESCRIPTIONS',
  VIEW_CUSTOMERS: 'VIEW_CUSTOMERS',
  EDIT_CUSTOMERS: 'EDIT_CUSTOMERS',
  VIEW_SUPPLIERS: 'VIEW_SUPPLIERS',
  EDIT_SUPPLIERS: 'EDIT_SUPPLIERS',
  VIEW_PURCHASES: 'VIEW_PURCHASES',
  EDIT_PURCHASES: 'EDIT_PURCHASES',
  VIEW_FINANCIALS: 'VIEW_FINANCIALS',
  EDIT_FINANCIALS: 'EDIT_FINANCIALS',
  VIEW_REPORTS: 'VIEW_REPORTS',
  ACCESS_POS: 'ACCESS_POS',
  VIEW_STOCK: 'VIEW_STOCK',
  EDIT_STOCK: 'EDIT_STOCK',
  VIEW_SETTINGS: 'VIEW_SETTINGS',
  EDIT_SETTINGS: 'EDIT_SETTINGS',
  VIEW_DELIVERIES: 'VIEW_DELIVERIES',
  UPDATE_DELIVERIES: 'UPDATE_DELIVERIES',
  MANAGE_USERS: 'MANAGE_USERS'
};

// Section 2 — Role Constants
export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  PHARMACIST: 'PHARMACIST',
  FINANCE: 'FINANCE',
  DISPATCH: 'DISPATCH',
  RIDER: 'RIDER',
  RECEIVING_BAY: 'RECEIVING_BAY'
};

// Section 3 — Role Permissions Map
export const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.ACCESS_ADMIN_DASHBOARD,
    PERMISSIONS.VIEW_PRODUCTS,
    PERMISSIONS.EDIT_PRODUCTS,
    PERMISSIONS.DELETE_PRODUCTS,
    PERMISSIONS.VIEW_ORDERS,
    PERMISSIONS.EDIT_ORDERS,
    PERMISSIONS.PROCESS_ORDERS,
    PERMISSIONS.VIEW_PRESCRIPTIONS,
    PERMISSIONS.VERIFY_PRESCRIPTIONS,
    PERMISSIONS.VIEW_CUSTOMERS,
    PERMISSIONS.EDIT_CUSTOMERS,
    PERMISSIONS.VIEW_SUPPLIERS,
    PERMISSIONS.EDIT_SUPPLIERS,
    PERMISSIONS.VIEW_PURCHASES,
    PERMISSIONS.EDIT_PURCHASES,
    PERMISSIONS.VIEW_FINANCIALS,
    PERMISSIONS.EDIT_FINANCIALS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.ACCESS_POS,
    PERMISSIONS.VIEW_STOCK,
    PERMISSIONS.EDIT_STOCK,
    PERMISSIONS.VIEW_SETTINGS,
    PERMISSIONS.EDIT_SETTINGS,
    PERMISSIONS.VIEW_DELIVERIES,
    PERMISSIONS.UPDATE_DELIVERIES,
    PERMISSIONS.MANAGE_USERS
  ],
  [ROLES.ADMIN]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_PRODUCTS,
    PERMISSIONS.EDIT_PRODUCTS,
    PERMISSIONS.DELETE_PRODUCTS,
    PERMISSIONS.VIEW_ORDERS,
    PERMISSIONS.EDIT_ORDERS,
    PERMISSIONS.PROCESS_ORDERS,
    PERMISSIONS.VIEW_PRESCRIPTIONS,
    PERMISSIONS.VERIFY_PRESCRIPTIONS,
    PERMISSIONS.VIEW_CUSTOMERS,
    PERMISSIONS.EDIT_CUSTOMERS,
    PERMISSIONS.VIEW_SUPPLIERS,
    PERMISSIONS.EDIT_SUPPLIERS,
    PERMISSIONS.VIEW_PURCHASES,
    PERMISSIONS.EDIT_PURCHASES,
    PERMISSIONS.VIEW_FINANCIALS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.ACCESS_POS,
    PERMISSIONS.VIEW_STOCK,
    PERMISSIONS.EDIT_STOCK
    // Note: Excluded MANAGE_USERS and EDIT_SETTINGS per spec
  ],
  [ROLES.MANAGER]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_PRODUCTS,
    PERMISSIONS.VIEW_ORDERS,
    PERMISSIONS.EDIT_ORDERS,
    PERMISSIONS.VIEW_CUSTOMERS,
    PERMISSIONS.EDIT_CUSTOMERS,
    PERMISSIONS.VIEW_SUPPLIERS,
    PERMISSIONS.EDIT_SUPPLIERS,
    PERMISSIONS.VIEW_PURCHASES,
    PERMISSIONS.EDIT_PURCHASES,
    PERMISSIONS.VIEW_FINANCIALS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_STOCK
    // Note: Missing EDIT_STOCK per spec, only VIEW_STOCK
  ],
  [ROLES.PHARMACIST]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_PRODUCTS,
    PERMISSIONS.VIEW_ORDERS,
    PERMISSIONS.EDIT_ORDERS,
    PERMISSIONS.VIEW_PRESCRIPTIONS,
    PERMISSIONS.VERIFY_PRESCRIPTIONS,
    PERMISSIONS.ACCESS_POS,
    PERMISSIONS.VIEW_STOCK
    // Note: Only VIEW_STOCK, no EDIT_STOCK per spec
  ],
  [ROLES.FINANCE]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_FINANCIALS,
    PERMISSIONS.EDIT_FINANCIALS,
    PERMISSIONS.VIEW_REPORTS
  ],
  [ROLES.DISPATCH]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_ORDERS,
    PERMISSIONS.PROCESS_ORDERS,
    PERMISSIONS.VIEW_STOCK,
    PERMISSIONS.VIEW_DELIVERIES,
    PERMISSIONS.UPDATE_DELIVERIES
  ],
  [ROLES.RIDER]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_ORDERS,
    PERMISSIONS.VIEW_DELIVERIES,
    PERMISSIONS.UPDATE_DELIVERIES
  ],
  [ROLES.RECEIVING_BAY]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_PRODUCTS,
    PERMISSIONS.EDIT_PRODUCTS,
    PERMISSIONS.DELETE_PRODUCTS,
    PERMISSIONS.VIEW_SUPPLIERS,
    PERMISSIONS.EDIT_SUPPLIERS,
    PERMISSIONS.VIEW_PURCHASES,
    PERMISSIONS.EDIT_PURCHASES,
    PERMISSIONS.VIEW_STOCK,
    PERMISSIONS.EDIT_STOCK
  ]
};

// Section 4 — Helper Functions
export const hasPermission = (userRole, permission) => {
  const userPermissions = ROLE_PERMISSIONS[userRole] || [];
  return userPermissions.includes(permission);
};

export const hasAnyPermission = (userRole, permissionsArray) => {
  const userPermissions = ROLE_PERMISSIONS[userRole] || [];
  return permissionsArray.some(permission => userPermissions.includes(permission));
};

export const hasAllPermissions = (userRole, permissionsArray) => {
  const userPermissions = ROLE_PERMISSIONS[userRole] || [];
  return permissionsArray.every(permission => userPermissions.includes(permission));
};

// Section 5 — Role Dashboard Map
export const ROLE_DASHBOARD_ROUTES = {
  [ROLES.SUPER_ADMIN]: '/dashboard',
  [ROLES.ADMIN]: '/dashboard',
  [ROLES.MANAGER]: '/dashboard/manager',
  [ROLES.PHARMACIST]: '/dashboard/pharmacist',
  [ROLES.FINANCE]: '/dashboard/finance',
  [ROLES.DISPATCH]: '/dashboard/dispatch',
  [ROLES.RIDER]: '/dashboard/rider',
  [ROLES.RECEIVING_BAY]: '/dashboard/receiving'
};

// TODO: Phase 2